title: "Arun 'Skanda' Rebbapragada"
author: "Arun Skanda"
email: "arun.skanda@outlook.com"
description: "Showcasing my achievements, projects, and experience."
theme: minima
baseurl: ""
url: "https://your-github-username.github.io"
